### ISSUE TITLE
Enabling Searching of Multiple Classes

### ISSUE THREAD

**Issue by noahc** [giniedp/fancygrid#13]
Before I dive into the code and see how hard this would be, do you have any thoughts on enabling fancygrid to search multiple classes of objects? Do you want a pull request to evaluate if I get it working?

**Comment by giniedp** [comment]
you mean, whether it is possible to search for lets say, "Users" and "Cars" for example? If that is the case, then there is no straight forward way to do that, since FancyGrid is just a wrapper around ActiveRecord. So all you results must inherit from one ActiveRecord class, which is bound to one single sql table.

However, it should be possible to write a custom Orm wrapper, that is able to fire an sql statement to get data directyl from an sql connection. You must then find a way to render each entry. Also there might be problems with a "table_name", which is resolved automaticly from the class name of the resulting object.

I would appreciate a pull request, if you get it working.

**Comment by noahc** [comment]
Yes, exactly. 

I started to go down the build my own ORM wrapper around fancy grid. Another advantage of the ORM wrapper approach would be that I could make it respect nested controllers. For example, I noticed that owners/3/cars displays all cars, not just those owned by owner with ID 3. 

EDIT: Found https://github.com/giniedp/fancygrid/wiki/HowTo-%3A-Handle-complex-queries which solves the problem above of not being able to display just the cars owned by Owner  with ID 3.

**Comment by giniedp** [comment]
You can already do the scope to an owner. You just have to add the query inside the find block. You can also have conditional conditions, for example

```
...
g.find do |query|
    query.where(:id => params[:id]) if params[:id].present?
end
...
```
