### ISSUE TITLE
Trashcan Icon?

### ISSUE THREAD

**Issue by noahc** [giniedp/fancygrid#8]
Some of our developers have issues with the trashcan icon and people being afraid their going to delete everything on the page. I was wondering if you could tell me where you got the icons so I can change them locally or would you consider changing the icon?

**Comment by giniedp** [comment]
the icons are the free version of http://glyphicons.com/ (i still need to point it out in the readme)
i used a base64 compressed sprite sheet image in the CSS, its the same as used in twitter bootstrap.
http://twitter.github.com/bootstrap/base-css.html#icons
i wouldnt change the icon in this project, but encurage you to do it in your custom CSS.

**Comment by noahc** [comment]
This is a topic I'm not too familiar with. How would I go about changing this in the css? 

I see all the base64 encodings, but when I use a service like http://www.miraclesalad.com/webtools/image_encoder.php with downloads from http://glyphicons.com/ I can't get my encodings to match yours. 

I've tried adding classes like " icon-cog" taken from the twitter bootstrap example like <li class="fg-button icon-cog" title="Reset"></li> but that doesn't seem to work.

Can you point me in the right direction?

**Comment by giniedp** [comment]
you can override the CSS rules to make the one button display something different. For that you dont have to replace the bas64 encoded spritesheet that is used by spritespin. Just download the icon you want to display, put it where your custom CSS can find it, use that as background image for that particular button. Make sure that your custom CSS is loaded after the fancygrid CSS or make your CSS rules more strong. Otherwise ask any of your team members who is familiar with CSS
